/**
 * POST /api/events/suggest-description
 * Given an event title (+ optional category/location/organiserId), returns a
 * suggested description generated by Claude.
 *
 * Style learning: if `organiserId` is supplied, fetches the organiser's last 5
 * event descriptions and uses them as few-shot examples so the AI mirrors the
 * way they actually write — vocabulary, sentence length, tone, level of formality.
 */
import { NextRequest, NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';
import { prisma } from '@/lib/db';
import { isAiDisabled, addApiUsage } from '@/lib/demo-spend';

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY || '' });

export async function POST(request: NextRequest) {
  if (!process.env.ANTHROPIC_API_KEY) {
    return NextResponse.json({ error: 'AI not configured.' }, { status: 500 });
  }
  if (await isAiDisabled()) {
    return NextResponse.json(
      { error: 'AI is currently unavailable — demo credit exhausted.' },
      { status: 503 }
    );
  }

  const body = await request.json();
  const title: string       = (body.title        ?? '').trim();
  const category: string    = (body.category     ?? '').trim();
  const location: string    = (body.location     ?? '').trim();
  const organiserId: string = (body.organiserId  ?? '').trim();

  if (!title || title.length < 3) {
    return NextResponse.json({ error: 'Title too short.' }, { status: 400 });
  }

  // ── Style learning: fetch organiser's past descriptions ────────────────────
  let pastDescriptions: string[] = [];
  if (organiserId) {
    try {
      const pastEvents = await prisma.event.findMany({
        where: { organiserId },
        select: { title: true, description: true },
        orderBy: { createdAt: 'desc' },
        take: 5,
      });
      pastDescriptions = pastEvents
        .map((e) => e.description.trim())
        .filter((d) => d.length > 30);
    } catch { /* non-fatal */ }
  }

  // Build style context block
  const styleBlock = pastDescriptions.length >= 2
    ? `\n\nIMPORTANT — this organiser has written the following descriptions before. Study their writing style carefully: their sentence structure, vocabulary, level of enthusiasm, use of punctuation, and tone. Write the new description in exactly the same style — it should sound like it came from the same person.\n\nExamples:\n${pastDescriptions.map((d, i) => `${i + 1}. "${d}"`).join('\n')}`
    : '';

  const contextParts: string[] = [];
  if (category) contextParts.push(`Category: ${category}`);
  if (location) contextParts.push(`Venue: ${location}`);
  const contextBlock = contextParts.length ? `\n${contextParts.join('\n')}` : '';

  const styleInstruction = pastDescriptions.length >= 2
    ? 'Match the organiser\'s established writing style exactly (see examples above).'
    : 'Write in second person ("Join us…" / "Don\'t miss…"), enthusiastic but professional, suitable for a TCD student audience.';

  const prompt = `You are helping a Trinity College Dublin society organiser write an event description.

Event title: "${title}"${contextBlock}${styleBlock}

Write a concise, engaging event description (2–3 sentences). ${styleInstruction} Output only the description text — no headings, no bullet points, no quotes.`;

  try {
    const response = await anthropic.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 220,
      messages: [{ role: 'user', content: prompt }],
    });

    await addApiUsage(response.usage.input_tokens, response.usage.output_tokens);

    const suggestion =
      response.content.find((b) => b.type === 'text')?.text?.trim() ?? '';

    return NextResponse.json({ suggestion });
  } catch (err) {
    console.error('[suggest-description]', err);
    return NextResponse.json({ error: 'Failed to generate suggestion.' }, { status: 500 });
  }
}
