/**
 * POST /api/events/suggest-description
 * Given an event title (+ optional category/location), returns a suggested
 * description generated by Claude. Used by the "Think with AI" feature on
 * the create-event form.
 */
import { NextRequest, NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';
import { isAiDisabled, addApiUsage } from '@/lib/demo-spend';

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY || '' });

export async function POST(request: NextRequest) {
  if (!process.env.ANTHROPIC_API_KEY) {
    return NextResponse.json({ error: 'AI not configured.' }, { status: 500 });
  }

  if (await isAiDisabled()) {
    return NextResponse.json(
      { error: 'AI is currently unavailable — demo credit exhausted.' },
      { status: 503 }
    );
  }

  const body = await request.json();
  const title: string = (body.title ?? '').trim();
  const category: string = (body.category ?? '').trim();
  const location: string = (body.location ?? '').trim();

  if (!title || title.length < 3) {
    return NextResponse.json({ error: 'Title too short.' }, { status: 400 });
  }

  const contextParts: string[] = [];
  if (category) contextParts.push(`Category: ${category}`);
  if (location) contextParts.push(`Venue: ${location}`);
  const context = contextParts.length ? `\n${contextParts.join('\n')}` : '';

  const prompt = `You are helping a Trinity College Dublin society organiser write an event description.

Event title: "${title}"${context}

Write a concise, engaging event description for this TCD event. It should be 2–3 sentences, enthusiastic but professional, written in second person ("Join us…" / "Don't miss…"), and suitable for a student audience. Output only the description text — no headings, no bullet points, no quotes.`;

  try {
    const response = await anthropic.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 200,
      messages: [{ role: 'user', content: prompt }],
    });

    await addApiUsage(response.usage.input_tokens, response.usage.output_tokens);

    const suggestion =
      response.content.find((b) => b.type === 'text')?.text?.trim() ?? '';

    return NextResponse.json({ suggestion });
  } catch (err) {
    console.error('[suggest-description]', err);
    return NextResponse.json({ error: 'Failed to generate suggestion.' }, { status: 500 });
  }
}
